### PR TITLE
get testing solr config files from exhibits_solr_conf

### PR DESCRIPTION
**Pull request by ndushay**
* add rubocop and hound
* take rubocop autofixes

connects to sul-dlss/sul_exhibits_template#78

### CODE REVIEW

**Comment by cbeer** [comment]
I extracted (and merged) the rubocop changes in #29

**Comment by cbeer** [comment]
I've tried to debug the test failure here; the jetty logs had errors like:

> Error creating core [test_d48e3ae4abfe_shard1_replica1]: Could not load conf for core test_d48e3ae4abfe_shard1_replica1: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'solr.ICUFoldingFilterFactory'. Schema file is /configs/configuration1/schema.xml

I think I tracked it down to [SOLR-4852](https://issues.apache.org/jira/browse/SOLR-4852), and gave up on the `sharedLib` and just dumped the needed jars into `solr/lib`.

**Comment by ndushay** [comment]
One of the reasons I didn't catch this was I was getting a diff error locally, in the same test, even when travis was passing.  And I'm still getting it:

1) Exhibit Request Workflow creates an exhibit
     Failure/Error: expect(File).to exist dir
       expected File to exist
     # ./spec/features/integration_spec.rb:31:in `block (2 levels) in <top (required)>'

it can't find the 'current' directory in the deployed exhibit.  Any clues?

**Comment by ndushay** [comment]
I've noticed vendor/internal-bundle has ruby-2.2.0  -- does that matter?

**Comment by ndushay** [comment]
perhaps this from the deploy.log?

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host localhost: bundle exit status: 1280
bundle stdout: An error occurred while installing mysql2 (0.3.20), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.20'` succeeds before bundling.
bundle stderr: Nothing written
```

**Comment by cbeer** [comment]
What do you get if you just run: `gem install mysql2 -v '0.3.20'`?

**Comment by ndushay** [comment]
I just noticed that rake spec is being run twice - maybe the second time is from spec/internal?  Trying to figure it out.

**Comment by cbeer** [comment]
We've seen rspec run twice before in other projects. It's something like rspec injecting a default task before we get our hands on it.

**Comment by ndushay** [comment]
so do we now need to load jettywrapper in the Rakefile?  I don't understand why load_tasks isn't loading it.

**Comment by ndushay** [comment]
@cbeer:  i think this is ready now!  yay!

**Pull request merged**
